litreview/litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'reviews/',
        include(('reviews.urls', 'reviews'), namespace='reviews')
    ),
    path(
        '',
        include(
            ('authentification.urls', 'authentification'),
            namespace='authentification'
        )
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview/reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask, name='ask'),
    path('create/', views.create, name='create'),
    path('create/<int:ticket_id>/', views.create, name='create'),
    path('edit/<int:review_id>/', views.edit, name='edit'),
    path(
        'edit_ticket/<int:ticket_id>/',
        views.edit_ticket,
        name='edit_ticket'
    ),
    path(
        'delete_review/<int:review_id>/',
        views.delete_review,
        name='delete_review'
    ),
    path(
        'delete_ticket/<int:ticket_id>/',
        views.delete_ticket,
        name='delete_ticket'
    ),
    path('me/', views.user_posts, name="me")
]

litreview/reviews/models.py
import os
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string


def rename_image(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (
        instance.user.id,
        get_random_string(8).lower(),
        ext
    )
    return os.path.join('tickets', filename)


# Create your models here.
class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, upload_to=rename_image)
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(0),
        MaxValueValidator(5)
    ])
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

litreview/reviews/forms.py
from django import forms


class TicketCreateForm(forms.Form):
    title = forms.CharField(label="Titre")
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    image = forms.ImageField(required=False)

    title.widget.attrs.update({'class': 'form-control'})
    image.widget.attrs.update({'class': 'form-control'})


class ReviewForm(forms.Form):
    headline = forms.CharField(label="Titre")
    rating = forms.ChoiceField(
        label="Note",
        widget=forms.RadioSelect,
        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]
    )
    body = forms.CharField(
        label="Commentaire",
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )

    headline.widget.attrs.update({'class': 'form-control'})
    rating.widget.attrs.update({'class': 'form-check-input'})

litreview/reviews/views.py
from django.shortcuts import redirect, render
from django.db.models import Q, CharField, Value
from itertools import chain

from .models import Ticket, Review
from .forms import TicketCreateForm, ReviewForm
from authentification.models import UserFollows


# Create your views here.
def index(request):

    followed_users = UserFollows.objects.filter(user__exact=request.user)
    tickets = Ticket.objects.filter(
        Q(user__id__in=followed_users.values_list('followed_user'))
        | Q(user__exact=request.user)
    )
    reviews = Review.objects.filter(
        Q(user__id__in=followed_users.values_list('followed_user'))
        | Q(user__exact=request.user)
    )

    tickets = tickets.annotate(content_type=Value('TICKET', CharField()))
    reviews = reviews.annotate(content_type=Value('REVIEW', CharField()))

    posts = sorted(
        chain(reviews, tickets),
        key=lambda post: post.time_created,
        reverse=True
    )

    return render(request, 'reviews/index.html', {'posts': posts})


def ask(request):
    if request.method == "POST":
        form = TicketCreateForm(request.POST, request.FILES)

        if form.is_valid():
            req = Ticket()
            req.title = form.cleaned_data['title']
            req.description = form.cleaned_data['description']
            req.image = form.cleaned_data['image']
            req.user = request.user
            req.save()
            return redirect('reviews:index')
    else:
        form = TicketCreateForm()
    return render(request, 'reviews/ask.html', {'form': form})


def create(request, ticket_id=None):
    context = {}

    if ticket_id is not None:
        ticket = Ticket.objects.get(id__exact=ticket_id)
        as_reviewed = Review.objects.filter(
            user__exact=request.user,
            ticket_id__exact=ticket_id
        )
        if len(as_reviewed) > 0:
            return redirect('reviews:index')
        context['ticket'] = ticket
        context['form'] = ReviewForm()
    else:
        context["ticket_form"] = TicketCreateForm()
        context['form'] = ReviewForm()

    if request.method == "POST":
        form = ReviewForm(request.POST)

        ticket = None
        if ticket_id is not None:
            ticket = Ticket.objects.get(id__exact=ticket_id)
        else:
            form2 = TicketCreateForm(request.POST, request.FILES)

            if form2.is_valid():
                req = Ticket()
                req.title = form2.cleaned_data['title']
                req.description = form2.cleaned_data['description']
                req.image = form2.cleaned_data['image']
                req.user = request.user
                req.save()
                ticket = req

        if form.is_valid():
            rev = Review()
            rev.headline = form.cleaned_data['headline']
            rev.body = form.cleaned_data['body']
            rev.rating = form.cleaned_data['rating']
            rev.ticket = ticket
            rev.user = request.user
            rev.save()
            return redirect('reviews:index')

    return render(request, 'reviews/create.html', context)


def edit(request, review_id: int):
    review = Review.objects.get(id__exact=review_id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review.headline = form.cleaned_data['headline']
            review.body = form.cleaned_data['body']
            review.rating = form.cleaned_data['rating']
            review.save()
            return redirect('reviews:index')

    form = ReviewForm()
    form.fields['headline'].initial = review.headline
    form.fields['body'].initial = review.body
    form.fields['rating'].initial = review.rating

    return render(
        request,
        'reviews/edit.html',
        {
            'form': form,
            'review': review,
            'ticket': Ticket.objects.get(id__exact=review.ticket.id)
        }
    )


def edit_ticket(request, ticket_id: int):
    ticket = Ticket.objects.get(id__exact=ticket_id)

    if request.method == "POST":
        form = TicketCreateForm(request.POST, request.FILES)
        if form.is_valid():
            ticket.title = form.cleaned_data['title']
            ticket.description = form.cleaned_data['description']
            if form.cleaned_data['image'] is False:
                ticket.image = None
            elif form.cleaned_data['image'] is not None:
                ticket.image = form.cleaned_data['image']
            ticket.save()
            return redirect('reviews:index')

    form = TicketCreateForm()
    form.fields['title'].initial = ticket.title
    form.fields['description'].initial = ticket.description
    form.fields['image'].initial = ticket.image

    return render(
        request,
        'reviews/ask.html',
        {
            'form': form,
            'ticket': ticket
        }
    )


def delete_review(request, review_id: int):
    rev = Review.objects.get(id__exact=review_id)
    rev.delete()

    return redirect('reviews:me')


def delete_ticket(request, ticket_id: int):
    ticket = Ticket.objects.get(id__exact=ticket_id)

    ticket.delete()

    return redirect('reviews:me')


def user_posts(request):
    tickets = Ticket.objects.filter(user__exact=request.user)
    reviews = Review.objects.filter(user__exact=request.user)

    tickets = tickets.annotate(content_type=Value('TICKET', CharField()))
    reviews = reviews.annotate(content_type=Value('REVIEW', CharField()))

    posts = sorted(
        chain(reviews, tickets),
        key=lambda post: post.time_created,
        reverse=True
    )

    return render(request, 'reviews/me.html', {'posts': posts})

litreview/reviews/templates/reviews/ask.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-10 offset-2">
		<h4 class="text-center">Créer un ticket</h4>

		<form enctype="multipart/form-data" action="{% if ticket is not None %}{% url 'reviews:edit_ticket' ticket.id %}{% else %}{% url 'reviews:ask' %}{% endif %}" method="post">
			{% csrf_token %}
			{{ form }}
			{% if ticket is not None and ticket.image %}
				<img src="{% get_media_prefix %}{{ ticket.image }}" alt="ticket_image" class="img-thumbnail w-25">
			{% endif %}
			<button type="submit" class="btn btn-primary float-end">Envoyer</button>
		</form>
	</div>
</div>
{% endblock content %}

litreview/reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-10 offset-2">
		<h4 class="text-center">Créer une critique</h4>
		<form enctype="multipart/form-data" action="
			{% if ticket is not None %}
				{% url 'reviews:create' ticket.id %}
			{% else %}
				{% url 'reviews:create' %}
			{% endif %}"
			method="post">

			{% csrf_token %}
			{% if ticket is not None %}
				<div class="ticket border border-dark p-1">
					Vous êtes en train de poster en réponse à
					<div class="ticket-infos border border-dark col-10 offset-1">
						<div class="header d-flex p-2">
							<div class="requested_by me-auto">
								{% if ticket.user == request.user %}
									Vous avez demander une critique
								{% else %}
									{{ ticket.user.username }} a demandé une critique
								{% endif %}
							</div>
							<div class="date">
								{{ ticket.time_created }}
							</div>
						</div>
						<div class="title border-bottom border-light ps-2">
							{{ ticket.title }}
						</div>
						<div class="description ps-2">
							{{ ticket.description }}
						</div>
						{% if ticket.image != '' %}
							<div class="image">
								<img src="{% get_media_prefix %}{{ ticket.image }}" alt="ticket_image" class="img-thumbnail w-25">
							</div>
						{% endif %}
					</div>
				</div>
			{% else %}
				<div class="border border-dark p-2">
					{{ ticket_form }}
				</div>
			{% endif %}
			<div class="review border border-dark p-2">
				<div class="mb-2">
					<label for="{{ form.headline.id_for_label }}">{{ form.headline.label }}</label>
					{{ form.headline }}
				</div>

				<div>{{ form.rating.label }}</div>
				{% for radio in form.rating %}
					<div class="form-check form-check-inline">
						{{ radio }}
						<label for="{{ radio.id_for_label }}">{{ radio.label }}</label>
					</div>
				{% endfor %}

				<div class="mb-2 mt-2">
					<label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
					{{ form.body }}
				</div>
				<button type="submit" class="btn btn-primary">Envoyer</button>
			</div>
		</form>
	</div>
</div>
{% endblock content %}

litreview/reviews/templates/reviews/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-10 offset-2">
		<h4 class="text-center">Éditer ma critique</h4>

		{% if ticket is not None %}
			<div class="ticket border border-dark p-1">
				Vous êtes en train de poster en réponse à
				<div class="ticket-infos border border-dark col-10 offset-1">
					<div class="header d-flex p-2">
						<div class="requested_by me-auto">
							{% if ticket.user == request.user %}
								Vous avez demander une critique
							{% else %}
								{{ ticket.user.username }} a demandé une critique
							{% endif %}
						</div>
						<div class="date">
							{{ ticket.time_created }}
						</div>
					</div>
					<div class="title border-bottom border-light ps-2">
						{{ ticket.title }}
					</div>
					<div class="description ps-2">
						{{ ticket.description }}
					</div>
					{% if ticket.image != '' %}
						<div class="image">
							<img src="{% get_media_prefix %}{{ ticket.image }}" alt="ticket_image" class="img-thumbnail w-25">
						</div>
					{% endif %}
				</div>
			</div>
		{% endif %}
		<div class="review border border-dark p-2">
			<form action="{% url 'reviews:edit' review.id %}" method="post">
				{% csrf_token %}
				<div class="mb-2">
					<label for="{{ form.headline.id_for_label }}">{{ form.headline.label }}</label>
					{{ form.headline }}
				</div>

				<div>{{ form.rating.label }}</div>
				{% for radio in form.rating %}
					<div class="form-check form-check-inline">
						{{ radio }}
						<label for="{{ radio.id_for_label }}">{{ radio.label }}</label>
					</div>
				{% endfor %}

				<div class="mb-2 mt-2">
					<label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
					{{ form.body }}
				</div>
				<button type="submit" class="btn btn-primary">Envoyer</button>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

litreview/reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-8 offset-2">
		<a href="{% url 'reviews:ask' %}" class="btn btn-primary btn-lg">Demander une critique</a>
		<a href="{% url 'reviews:create' %}" class="btn btn-primary btn-lg float-end">Créer une critique</a>
	</div>
	<div class="col-8 offset-2 mt-3">
		{% for post in posts %}
			{% if post.content_type == 'TICKET' %}
				{% include 'ticket_snippet.html' %}
			{% elif post.content_type == 'REVIEW' %}
				{% include 'review_snippet.html' %}
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock content %}

litreview/reviews/templates/reviews/me.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-8 offset-2 mt-2">
		{% for post in posts %}
			{% if post.content_type == 'TICKET' %}
				{% include 'ticket_snippet.html' %}
			{% elif post.content_type == 'REVIEW' %}
				{% include 'review_snippet.html' %}
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock content %}