litreview/authentification/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.auth_logout, name="logout"),
    path('follows/', views.follows, name="follows"),
    path('unfollow/<int:user_id>/', views.delete_follow, name="unfollow")
]

litreview/litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'reviews/',
        include(('reviews.urls', 'reviews'), namespace='reviews')
    ),
    path(
        '',
        include(
            ('authentification.urls', 'authentification'),
            namespace='authentification'
        )
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview/reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask, name='ask'),
    path('create/', views.create, name='create'),
    path('create/<int:ticket_id>/', views.create, name='create'),
    path('edit/<int:review_id>/', views.edit, name='edit'),
    path(
        'edit_ticket/<int:ticket_id>/',
        views.edit_ticket,
        name='edit_ticket'
    ),
    path(
        'delete_review/<int:review_id>/',
        views.delete_review,
        name='delete_review'
    ),
    path(
        'delete_ticket/<int:ticket_id>/',
        views.delete_ticket,
        name='delete_ticket'
    ),
    path('me/', views.user_posts, name="me")
]

litreview/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<title>LITReview</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
		<div class="container-fluid">
			<a class="navbar-brand" href="#">LITReview</a>
			
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarContent">
				<ul class="navbar-nav">
					

					{% if not user.is_authenticated %}
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'reviews:index' %}">Accueil</a>
						</li>
					{% else %}

						<li class="nav-item active">
							<a class="nav-link" href="{% url 'reviews:index' %}">Flux</a>
						</li>

						<li class="nav-item active">
							<a class="nav-link" href="{% url 'reviews:me' %}">Posts</a>
						</li>

						<li class="nav-item active">
							<a class="nav-link" href="{% url 'authentification:follows' %}">Abonnements</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'authentification:logout' %}">Déconnexion</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		{% block content %}{% endblock %}
	</div>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

litreview/templates/review_snippet.html
{% load static %}
{% load range %}
<div class="col-12 mb-3">
	<div class="border border-dark">
		<div class="header d-flex p-2">
			<div class="requested_by me-auto">
				{% if post.user == request.user %}
					Vous avez publier une critique
				{% else %}
					{{ post.user.username }} a publier une critique
				{% endif %}
			</div>
			<div class="date">
				{{ post.time_created }}
			</div>
		</div>
		<div class="title fw-bold border-bottom border-light ps-2">
			{{ post.headline }} - 
			{% for i in post.rating|range %}
				<i class="fas fa-star"></i>
			{% endfor %}
			{% for i in post.rating|range:5 %}
				<i class="far fa-star"></i>
			{% endfor %}
		</div>
		<div class="description ps-2">
			{{ post.body }}
		</div>
		{% if post.ticket is not None %}
			<div class="ticket border border-dark p-2 m-2">
				Ticket - {{ post.ticket.user.username }}
				<div class="title">
					{{ post.ticket.title }}
				</div>
				{% if post.ticket.image %}
					<div class="image">
						<img src="{% get_media_prefix %}{{ post.ticket.image }}" alt="ticket_image" class="img-thumbnail w-25">
					</div>
				{% endif %}
			</div>
		{% endif %}
		{% if post.user == request.user %}
			<a href="{% url 'reviews:edit' post.id %}" class="btn btn-warning m-1">Éditer ma critique</a>
			<a href="{% url 'reviews:delete_review' post.id %}" class="btn btn-danger m-1">Supprimer ma critique</a>
		{% endif %}
	</div>
</div>

litreview/templates/ticket_snippet.html
{% load static %}
<div class="col-12 mb-3">
	<div class="border border-dark">
		<div class="header d-flex p-2">
			<div class="requested_by me-auto">
				{% if post.user == request.user %}
					Vous avez demander une critique
				{% else %}
					{{ post.user.username }} a demandé une critique
				{% endif %}
			</div>
			<div class="date">
				{{ post.time_created }}
			</div>
		</div>
		<div class="title border-bottom border-light ps-2">
			{{ post.title }}
		</div>
		<div class="description ps-2">
			{{ post.description }}
		</div>
		{% if post.image and post.image != '' %}
			<div class="image">
				<img src="{% get_media_prefix %}{{ post.image }}" alt="ticket_image" class="img-thumbnail w-25">
			</div>
		{% endif %}
		{% if post.user == request.user %}
			<a href="{% url 'reviews:edit_ticket' post.id %}" class="btn btn-warning m-1">Éditer ma demande</a>
			<a href="{% url 'reviews:delete_ticket' post.id %}" class="btn btn-danger m-1">Supprimer ma demande</a>
		{% else %}
			<a href="{% url 'reviews:create' post.id %}" class="btn btn-secondary">Créer une critique</a>
		{% endif %}
	</div>
</div>